from typing import Protocol

from backend.app.models import HostConfig


class HostRepository(Protocol):
    def load_hosts(self) -> list[HostConfig]: ...

    def get_host(self, host_id: str) -> HostConfig | None: ...

    def add_host(self, host: HostConfig) -> HostConfig: ...

    def update_host(self, host_id: str, updates: dict) -> HostConfig: ...

    def delete_host(self, host_id: str) -> None: ...
